### ISSUE TITLE
Already On Playstore under name Pachisi

### ISSUE THREAD

**Issue by khalilbsaibes** [dinosaadeh/Barjis#1]
https://play.google.com/store/search?q=Pachisi&c=apps

**Comment by dinosaadeh** [comment]
Wow.. je ne sais pas comment t'as chercher pour trouver ce nom.. Enfin, rien n'empêche de la redévelopper. On peut toujours voir ce que les autres ont fait et inventer de meilleurs idées!

**Comment by ammaroveold** [comment]
the game is not the same 100%

**Comment by dinosaadeh** [comment]
whether the same or not, it is fun to develop it 😄
