### ISSUE TITLE
Give Hint to Pawn Available Moves

### ISSUE THREAD

**Issue by dinosaadeh** [dinosaadeh/Barjis#12]
When a player selects a pawn to move, check its available moves and include the yellow triangle at the destination cells it can reach. This triangle needs to be at the edge of the cell (as per the design). At times you will need to smartly position it on the screen and rotate it.

**Comment by najidagher** [comment]
ill be taking care of this issue.

**Comment by dinosaadeh** [comment]
I'm deleting this one.. It is a duplicate and you're already working on it.
