### ISSUE TITLE
Dimbo Font Problem

### ISSUE THREAD

**Issue by dinosaadeh** [dinosaadeh/Barjis#6]
The font used in the design is not showing properly within the game.. After some investigation I think [Hiero](https://libgdx.badlogicgames.com/tools.html) didn't generate the PNG properly.. We need to see if we can make it work by letting another font engine render it instead of Java (FreeType).

I doubt that the problem is with this font in specific since other system fonts are not rendering properly either. The only one rendering properly is Arial coz it is the default for libgdx.

If we fail to render this font, we may need to find an alternative font.

**Comment by dinosaadeh** [comment]
@aliammar7 please deal with this issue. The last solution I did was generate a font of size 40 instead of 22 and then in code I scaled it down. Please try finding a solution (even ask libgdx irc chat: [](http://webchat.freenode.net/)).. maybe I'm doing something wrong. But let's have this font correctly on the screen.

Copy the below to a text file named dimbo.hiero and open it in hiero to see the effects I applied from the design. To sum up, the font has a gradient color from bottom to top (#e3dead, #FFFFFF) + it has an outline of this color #c34960.

```
font.name=Dimbo
font.size=30
font.bold=false
font.italic=false
font.gamma=1.8
font.mono=false

font2.file=
font2.use=false

pad.top=1
pad.right=1
pad.bottom=1
pad.left=1
pad.advance.x=-2
pad.advance.y=-2

glyph.native.rendering=false
glyph.page.width=512
glyph.page.height=512
glyph.text=ABCDEFGHIJKLMNOPQRSTUVWXYZ\nabcdefghijklmnopqrstuvwxyz\n1234567890 \n"!`?'.,;:()[]{}<>|/@\^$-%+=#_&~*

effect.class=com.badlogic.gdx.tools.hiero.unicodefont.effects.ColorEffect
effect.Color=ffffff

effect.class=com.badlogic.gdx.tools.hiero.unicodefont.effects.OutlineEffect
effect.Color=c34960
effect.Width=3.0
effect.Join=2

effect.class=com.badlogic.gdx.tools.hiero.unicodefont.effects.GradientEffect
effect.Top color=ffffff
effect.Bottom color=e3dead
effect.Offset=0
effect.Scale=1.0
effect.Cyclic=false
```

**Comment by ammaroveold** [comment]
@dinosaadeh 
please see the fonts in this site //www.glyphite.com
