### ISSUE TITLE
Feature: Dice values layout and selection

### ISSUE THREAD

**Issue by dinosaadeh** [dinosaadeh/Barjis#8]
We need to implement a good display of the dice values
- Every value has a multiplier (2xDest)
- There is a + between values.
  Place rectangles that interact with touch. Every rectangle should dynamically cover every move value (2xDest, 3, Banj makes 3 rectangles with different dimensions).. When the user touches a value, it shows in `Gdx.app.log(TAG, "The value touched is: " + value);`.

**Comment by dinosaadeh** [comment]
@najidagher I just remembered something.. When a value is fully played, you can overlay the value with this image to show it as disabled (no longer playable) --> disabled-text-overlay from sprites.

**Comment by najidagher** [comment]
#8 done noting that there is a prob when getting the TextWidth, i think its something related to the font.
I committed the changes, but I'll keep searching.
