### ISSUE TITLE
Show triangle hint on the path

### ISSUE THREAD

**Issue by dinosaadeh** [dinosaadeh/Barjis#9]
When a user clicks a pawn to move, we're already taking care of enabling/disabling moves that a pawn can move (text buttons).. Based on the moves a person can make, we need to show a triangle on the path showing the player where he will reach for each possible move. Triangle is part of the design.

**Comment by najidagher** [comment]
Is anyone working on this issue?

**Comment by dinosaadeh** [comment]
Seems not @najidagher .. did you finish the dice collision?

**Comment by najidagher** [comment]
Nops Still trying to make it more real

**Comment by najidagher** [comment]
#9 done.
Hints are being showed for all pawns...we might need to show hints for the selected pawn only

**Comment by dinosaadeh** [comment]
Most definitely it shows only when a pawn is clicked.. Otherwise it won't
serve its purpose.
